### ISSUE TITLE
which script is better

### ISSUE THREAD

**Issue by panshengjie** [John-Vision/Intel-7260-Wifi-Fix#1]
**hi john**,
    I have the same problem for a long time.  The situiation here is  we use AC7260 on a robot, which running 7x24 all day&night. For some reason we can't replace wifi card that easy, so better the software fix.
   my experience is that this card , works stable in single 5G wifi(APs), probabbly unstable in 2.4G&5G mixed wfi (with same SSID).
  I have found two scripts that can resume wifi without reboot: one is yours , another is below.   could you help me which one is better for my situiation, many thanks~

````
#!/bin/sh
# If an interface name was not passed in then assume that wlo1 is the interface name.
if [ -z "$1" ]; then
    interface="wlo1"
else
    interface=$1
fi

# Figure out what pci slot Linux has assigned the Network controller: Intel Corporation Wireless 7260
wirelessPCI=$(lspci |grep "Wireless 7260")
pci=$(echo ${wirelessPCI} | awk '{ print $1 }')
devicePath="/sys/bus/pci/devices/0000:$pci/remove"

# Not the best solution as this script can hang.
# But since if this script fails the ONLY way to revive the wifi anyway is a reboot...
# Feel free to improve the script if you have the scriptfu ninja skills to do so.
while true; do

    # Tell Linux to remove the wifi card from the PCI device list only if it exists in the first place.
    if [ -f $devicePath ]; then
        echo 1 | sudo tee $devicePath > /dev/null
        sleep 1
    fi

    # Reprobe the driver modules in case we have removed them in a failed attempt to wake the network card.
    sudo modprobe iwlmvm
    sudo modprobe iwlwifi

    # Try to have Linux bring the network card back online as a PCI device.
    echo 1 | sudo tee /sys/bus/pci/rescan > /dev/null
    sleep 1

    # Check if Linux managed to bring the network card back online as a PCI device.
    if [ -f $devicePath ]; then

        # Looks like we are back in business.
        # So we try to set the PCI slot with some voodoo I don't understand that the Intel devs told me to try.
        # https://bugzilla.kernel.org/show_bug.cgi?id=191601
        sudo setpci -s $pci 0x50.B=0x40

        # Bring the wireless network interface up.
        sudo ifconfig $interface up

        # Did the wifi interface actually go live?
        exitCode=$?
        if [ $exitCode -eq 0 ];then

            # Not sure why in the hell this is not the default for wireless intefaces.
            # It is well documented that: (power_management === ON) === Wifi-Stupidity
            sudo iwconfig $interface power off

            # The exit code will be the exit code of our attempt at turning power management off for $interface/wlan0.
            break
        fi
    else
        # It's worse than that the wifi's dead Jim! Dead Jim! Dead!
        # We tell Linux to remove the the wifi driver modules and loop back in an attempt to revive the wifi.
        sudo modprobe -r iwlmvm
        sudo modprobe -r iwlwifi
    fi
done
```

**Comment by John-Vision** [comment]
Both scripts are fairly similar, but my full solution also includes setting up a cron job which does seem to improve things further.
With that being said, I really do have to stress that certain 7260s just don't work well, and will give you problems regardless of any software fixes. Sometimes these cards WILL fail, no matter what.
In that case, I would STRONGLY suggest replacing the card, if at all possible. If you just cannot replace the card, then you should consider getting a usb wifi adapter. While I was trying to figure out the issues with my card I did that, and it worked great. Here's a link to the one I got on Amazon:

USB WIFI https://www.amazon.com/gp/product/B004Y6MIXS/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

I wish I could give you a better solution, but when using one of the bad 7260s you will have occasional failures, no matter what, although my solution will give you the best possible results. Even better, however, would be to use a USB solution like the one above, but even best of all would be to change the internal wifi card if you can. I wish I had better news for you.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by panshengjie** [comment]
Thanks a lot john~
I will do some test to check if this helps.
As you suggested, we are replacing wifi card in new robots.  And the script will be a temporary method for those running robots.
